language: node_js
node_js: "6.11.5"

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install karma-firefox-launcher

script: ". ./jake.sh loose=true capture=Firefox"

#notifications:
#  email:
#    on_success: always
